### ISSUE TITLE
Crawler exception "TypeError: string indices must be integers"

### ISSUE THREAD

**Issue by lhannest** [biothings/biothings_explorer_jsonld#12]
This endpoint is throwing an exception:
http://biothings.io/explorer/api/v2/crawler?input_type=kegg.pathway&input_value=hsa04950

```
Traceback (most recent call last):
  File "/home/ubuntu/opt/devpy3/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/ubuntu/opt/biothings_explorer_web/src/handlers/entitycrawler.py", line 302, in get
    results = exploreinput(input_type, input_value)
  File "/home/ubuntu/opt/biothings_explorer_web/src/handlers/entitycrawler.py", line 211, in exploreinput
    _output = jh.fetch_properties_by_association_in_nquads(nquads, association_list)
  File "/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/jsonld_processor.py", line 279, in fetch_properties_by_association_in_nquads
    object_values = self.fetch_object_value_by_predicate_value_in_nquads(nquads, _association)
  File "/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/jsonld_processor.py", line 247, in fetch_object_value_by_predicate_value_in_nquads
    nquads = nquads['@default']
TypeError: string indices must be integers
```

**Comment by kevinxin90** [comment]
@lhannest Thanks for pointing it out! It's currently fixed! You might try it out again!
