### ISSUE TITLE
OSError: Initializing from file failed

### ISSUE THREAD

**Issue by lhannest** [biothings/biothings_explorer_jsonld#13]
http://biothings.io/explorer/api/v2/crawler?input_type=mondo&input_value=0018911

```
Traceback (most recent call last):
  File "/home/ubuntu/opt/devpy3/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/ubuntu/opt/biothings_explorer_web/src/handlers/entitycrawler.py", line 308, in get
    results = exploreinput(input_type, input_value)
  File "/home/ubuntu/opt/biothings_explorer_web/src/handlers/entitycrawler.py", line 160, in exploreinput
    synonyms = IDConverter().find_synonym(input_value, input_type)
  File "/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/id_converter.py", line 70, in __init__
    self.registry = RegistryParser(readmethod='filepath', initialize=True)
  File "/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/api_registry_parser.py", line 47, in __init__
  File "/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/api_registry_parser.py", line 65, in read_id_mapping_file
  File "/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/utils.py", line 39, in readFile
  File "/home/ubuntu/opt/devpy3/lib/python3.5/site-packages/pandas/io/parsers.py", line 705, in parser_f
  File "/home/ubuntu/opt/devpy3/lib/python3.5/site-packages/pandas/io/parsers.py", line 445, in _read
  File "/home/ubuntu/opt/devpy3/lib/python3.5/site-packages/pandas/io/parsers.py", line 814, in __init__
  File "/home/ubuntu/opt/devpy3/lib/python3.5/site-packages/pandas/io/parsers.py", line 1045, in _make_engine
  File "/home/ubuntu/opt/devpy3/lib/python3.5/site-packages/pandas/io/parsers.py", line 1684, in __init__
  File "pandas/_libs/parsers.pyx", line 391, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 712, in pandas._libs.parsers.TextReader._setup_parser_source
OSError: Initializing from file failed
```

**Comment by lhannest** [comment]
Now it's giving a new error:

```
Traceback (most recent call last):
  File "/home/ubuntu/opt/devpy3/lib/python3.5/site-packages/tornado/web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/ubuntu/opt/biothings_explorer_web/src/handlers/entitycrawler.py", line 308, in get
    results = exploreinput(input_type, input_value)
  File "/home/ubuntu/opt/biothings_explorer_web/src/handlers/entitycrawler.py", line 209, in exploreinput
    nquads_list = jh.jsonld2nquads(jsonld_docs, alwayslist=True)
  File "/home/ubuntu/opt/biothings_explorer_web/src/biothings_explorer/jsonld_processor.py", line 105, in jsonld2nquads
    pool = multiprocessing.Pool(multiprocessing.cpu_count())
  File "/usr/lib/python3.5/multiprocessing/context.py", line 118, in Pool
    context=self.get_context())
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 150, in __init__
    self._setup_queues()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 244, in _setup_queues
    self._outqueue = self._ctx.SimpleQueue()
  File "/usr/lib/python3.5/multiprocessing/context.py", line 111, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 324, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.5/multiprocessing/context.py", line 66, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 163, in __init__
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 60, in __init__
OSError: [Errno 24] Too many open files
```

**Comment by kevinxin90** [comment]
Hi Lance,

Took some time to fix this problem! It's due to the multiprocessing module used in BioThings Explorer. I have fixed it and the error should not pop up again.

Thanks again for reporting that!
